@startuml
'https://plantuml.com/activity-diagram-beta

|Bruger|
start
:Lander på ordrer siden;
:Brugeren giver input;
|System|
switch (bruger input)
case (ny ordre)
    :Gem alle brugerens ordre i databasen;
    :Lav en ny ordre i databasen;
case (tilføj en til ordre)
    :Lav en kopi af den
    valgte ordre i databasen;
case (fjern en fra ordre)
    :Fjern en kopi af den
    valgte ordre i databasen;
case (gem ordrer)
    :Gem alle brugerens ordrer i datebasen;
case (bestil ordrer)
    :Updater alle brugerens ordrer;
endswitch
stop

@enduml
