@startuml
'https://plantuml.com/activity-diagram-beta

|Bruger|
start
:Lander på forsiden;
:Går til log ind;
repeat :Indtaster login;
|System|
backward :send brugeren tilbage;
repeat while (Findes et match i databasen?) is (Nej) not (Ja)
:Giv brugeren adgang og
 gem kontoen i session;
stop


@enduml
